/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
  safelist: [
    "bg-cyan-400",
    "bg-cyan-500",
    "bg-gradient-to-r",
    "from-cyan-500",
    "to-sky-500",
    "rounded-full",
    "hover:bg-cyan-400",
    "hover:bg-cyan-500",
    "text-cyan-400",
    "text-white",
    "border-cyan-400",
    "border-cyan-500",
    "hover:text-white",
    "hover:scale-105",
    "hover:shadow-cyan-500/50",
    "hover:border-cyan-400",
    "hover:drop-shadow-[0_0_16px_#38bdf8]",
    "focus:ring-2",
    "focus:ring-cyan-400",
    "focus:border-cyan-400",
    "focus:drop-shadow-[0_0_16px_#38bdf8]",
    "focus:scale-105",
    "transition-all",
    "duration-300",
    "group-hover:opacity-100",
    "group-hover:scale-105",
    "group-hover:text-cyan-300",
    "group-hover:border-cyan-300",
    "group-hover:bg-cyan-400/30",
    "group-hover:from-cyan-400/30",
    "group-hover:via-cyan-400/10",
    "group-hover:to-transparent",
    "group-hover:drop-shadow-[0_0_16px_#38bdf8]",
    "group-hover:scale-110",
    "group-hover:rotate-12",
    "group-hover:from-cyan-400",
    "group-hover:via-blue-400",
    "group-hover:to-fuchsia-400",
    "group-hover:w-32",
    "group-hover:w-4/5",
    "group-hover:scale-125",
    "group-hover:bg-cyan-400/20",
    "group-hover:blur-[4px]",
    "group-hover:opacity-100",
    "group-hover:animate-particle-float",
  ],
} 